import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Image
          src="https://web.atendare.com/images/logo/atendare_logo.svg"
          alt="Logo do Atendare"
          width={300}
          height={100}
          priority={true}
          style={{
            position: "absolute",
            bottom: "650px", // Fixa a 10px da borda inferior
            left: "50%", // Centraliza horizontalmente
            transform: "translateX(-50%)", // Ajusta para que o centro da imagem fique alinhado
            objectFit: "contain", // Garante que a imagem seja exibida proporcionalmente
            objectPosition: "center",
          }}
        />
      </body>
    </html>
  );
}
